packages:
  - name: docker
    type: docker
    srcs:
      - "package-libs.sh"
      - "startup.sh"
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/ide/code:${version}